openqasm/qe-compiler

- cmake/apple-clang.cmake
The build may fail on Apple Silicon if the `llvm-config` program is not available on the path. This results in an empty `LLVM_TARGET_TRIPLE` variable and the error:
```
clang: error: argument unused during compilation: '-arch arm64' [-Werror,-Wunused-command-line-argument]
```
This PR uses `find_program` to locate the llvm-config binary. cmake will raise an error if the binary is not located.
> Use find_program to locate llvm-config

- include/Frontend/OpenQASM3/OpenQASM3Frontend.h
- include/HAL/Compile/TargetCompilationManager.h
- include/HAL/Compile/ThreadedCompilationManager.h
- include/HAL/TargetSystem.h
- lib/API/api.cpp
- lib/Frontend/OpenQASM3/OpenQASM3Frontend.cpp
- lib/HAL/Compile/TargetCompilationManager.cpp
- lib/HAL/Compile/ThreadedCompilationManager.cpp
- lib/HAL/TargetSystem.cpp
- lib/QSSC.cpp
- releasenotes/notes/add-timing-manager-support-9de5e2407fc95330.yaml
- targets/systems/mock/MockTarget.cpp
- targets/systems/mock/test/static/integration/mlir/mlir-timing.mlir
Introduces support for the TimingManager which was a part of LLVM 17. This enables time tracing of (parallel) compilation across target systems. For example this is a report from the mock target.
```
===-------------------------------------------------------------------------===
... Execution time report ...
===-------------------------------------------------------------------------===
Total Execution Time: 0.0089 seconds
----User Time----  ----Wall Time----  ----Name----
0.0000 (  0.1%)    0.0000 (  0.2%)  build-config
0.0001 (  0.7%)    0.0001 (  1.3%)  build-target
0.0004 (  2.7%)    0.0004 (  4.7%)  parse-mlir
0.0000 (  0.1%)    0.0000 (  0.1%)  command-line-passes
0.0143 ( 91.6%)    0.0076 ( 85.3%)  build-qem
0.0142 ( 91.0%)    0.0075 ( 84.2%)    compile-payload
0.0011 (  7.2%) …
```
> Add support for TimingManager

- lib/Dialect/QUIR/Transforms/MergeParallelResets.cpp
- releasenotes/notes/parallel-reset-bottom-up-traversal-0ad69d49e9d6e6e1.yaml
Yields a roughly 3x performance improvement on my local machine.
> Switch to bottom up traversal in parallel reset

- test/Config/test-config.tst
This test is failing for debug builds as the output checks whether verification is enabled (which it is for debug builds). 
The REQUIRES will disable this test when asserts are enabled.
> Disable test-config.tst when using build with asserts.

- lib/API/api.cpp
We need to register the LLVM Dialect as a valid translation target. 
This had previously been done later in the pipeline, but since registering dialects is not thread safe, we need to register it earlier before we start the ThreadedCompilationManager.
> Register LLVM Dialect with the context.

- targets/systems/mock/Transforms/QubitLocalization.cpp
- targets/systems/mock/test/static/Conversion/QUIRToStd/llvmgen.mlir
- targets/systems/mock/test/static/Transforms/qubit-localization.mlir
NodeIDs for the module need to be created as unsigned integers. The getNodeId method assumes the IDs are unsigned and accesses the attributes as such. 
LLVM 17 has increased their type checking for this, so several tests are now failing with debug builds. This should resolve these problems.
> Use unsigned int for module NodeIDs.

- include/Conversion/QUIRToPulse/LoadPulseCals.h
- lib/Conversion/QUIRToPulse/LoadPulseCals.cpp
This fixes an assertion in the debug builds by registering the pulse dialect before the ThreadedCompilationManager is run.
> Register Pulse Dialect with LoadPulseCals pass.

- lib/Dialect/QUIR/Transforms/MergeCircuits.cpp
- releasenotes/notes/test-overlap-all-5d170626357867d6.yaml
- test/Dialect/QUIR/Transforms/merge-circuits.mlir
The `MergeCircuitsPass` assumed that the only quantum operation between `quir.call_circuits` operations would be `quir.barriers`. This assumption failed with the `BreakResetsPass` which currently inserts `quir.measure` and `quir.call_gate @x` in the `main` function. 
One way to fix this would be to adjust `BreakResetsPass` to be `--enable-circuits` aware. The alternative implemented here is to handle operations other than barriers between `quir.circuit_ops` and test for qubit overlap in the same way currently being applied to `quir.barriers`. 
This alternative was chosen so that existing and future passes would not be required to be "quir.circuit" aware and therefore `MergeCircuitsPass` would be more robust to that situation.
> Test for overlap with all quantum operations in MergeCircuitsPass

- lib/Conversion/QUIRToPulse/LoadPulseCals.cpp
Fixes clang-tidy error:
```
lib/Conversion/QUIRToPulse/LoadPulseCals.cpp:673:46: error: no header providing "mlir::DialectRegistry" is directly included [misc-include-cleaner,-warnings-as-errors]
57 | void LoadPulseCalsPass::getDependentDialects(DialectRegistry &registry) const {
|    
```
> Add header import to fix clang-tidy

- .github/CODEOWNERS
- .github/renos_updated.sh
- .github/workflows/clang_tidy_review_comments.yml
- .github/workflows/lint.yml
- .github/workflows/test.yml
- conan/qasm/conanfile.py
- conanfile.py
- requirements-dev.txt
Backports changes to the `.github` directory only from the main branch to the `release_v3.7` branch.
> [Backport 3.7] Backport CI changes to 3.7

- .github/CODEOWNERS
- .github/renos_updated.sh
- .github/workflows/clang_tidy_review_comments.yml
- .github/workflows/lint.yml
- .github/workflows/test.yml
- conan/qasm/conanfile.py
- conanfile.py
- requirements-dev.txt
Backports changes to the `.github` directory only from the main branch to the `release_v3.8` branch.
> [Backport 3.8] Backport CI changes to 3.8

- lib/Dialect/QUIR/Transforms/MergeCircuits.cpp
- releasenotes/notes/test-overlap-all-5d170626357867d6.yaml
- test/Dialect/QUIR/Transforms/merge-circuits.mlir
Handle quir operations in addition to barriers between quir.circuit_ops and test for qubit overlap in the same way currently being applied to quir.barriers.
> [Backport 3.7] Test for overlap with all quantum operations in MergeCircuitsPass (#244)

- lib/Dialect/QUIR/Transforms/MergeCircuits.cpp
- releasenotes/notes/test-overlap-all-5d170626357867d6.yaml
- test/Dialect/QUIR/Transforms/merge-circuits.mlir
Handle quir operations in addition to barriers between quir.circuit_ops and test for qubit overlap in the same way currently being applied to quir.barriers.
> [Backport 3.8] Test for overlap with all quantum operations in MergeCircuitsPass (#244)

- include/Config/EnvVarConfig.h
- include/Config/QSSConfig.h
- lib/API/api.cpp
- lib/Config/CLIConfig.cpp
- lib/Config/EnvVarConfig.cpp
- lib/Config/QSSConfig.cpp
- releasenotes/notes/add-max-threads-4073cc0b39df6d68.yaml
- test/Config/test-config.tst
Adds support for setting the maximum number of threads used by the qss-compiler's MLIR context. This can be done through the CLI option ``--max-threads=<uint>`` or the environment variable ``export QSSC_MAX_THREADS=<uint>``.
> Add support for setting the maximum number of threads

- include/API/api.h
- include/API/errors.h
- include/Arguments/Arguments.h
- include/Arguments/Signature.h
- include/Frontend/OpenQASM3/OpenQASM3Frontend.h
- include/HAL/Compile/TargetCompilationManager.h
- include/HAL/Compile/ThreadedCompilationManager.h
- include/HAL/TargetSystem.h
- lib/API/api.cpp
- lib/API/errors.cpp
- lib/Arguments/Signature.cpp
- lib/Frontend/OpenQASM3/OpenQASM3Frontend.cpp
- lib/HAL/Compile/TargetCompilationManager.cpp
- lib/HAL/Compile/ThreadedCompilationManager.cpp
- python_lib/qss_compiler/compile.py
- python_lib/qss_compiler/exceptions.py
- python_lib/qss_compiler/lib_enums.cpp
- releasenotes/notes/user-error-updates-3fe6706fbf8ffab8.yaml
This PR supersedes #211 
Adds diagnostic tracking to targets, updates the API to check for and emit diagnostics stored in the target, updates the python interface to raise exceptions based on returned diagnostics, and adds a new error/exception for sequences that are too long.
> Add diagnostic tracking to target and an error for too long sequences

- include/API/errors.h
- include/HAL/TargetSystem.h
- lib/API/errors.cpp
- python_lib/qss_compiler/compile.py
- python_lib/qss_compiler/exceptions.py
- python_lib/qss_compiler/lib_enums.cpp
- releasenotes/notes/control-system-resources-exceeded-error-d2a2c15c52fa02dd.yaml
This PR adds a new QSSControlSystemResourcesExceeded error category. This can be raised as an error whenever the compiler detects that an input circuit will exceed the resources of the control system, such as instruction or waveform memory.
I've also added a new `addDiagnostic()` method to the target system that prevents unnecessary copies of diagnostic objects from being made.
> Add control system resources exceeded error

- include/Dialect/QUIR/Transforms/MergeCircuitMeasures.h
- include/Dialect/QUIR/Transforms/Passes.h
- include/Dialect/QUIR/Transforms/RemoveUnusedCircuits.h
- lib/Dialect/QUIR/Transforms/CMakeLists.txt
- lib/Dialect/QUIR/Transforms/MergeCircuitMeasures.cpp
- lib/Dialect/QUIR/Transforms/MergeCircuits.cpp
- lib/Dialect/QUIR/Transforms/Passes.cpp
- lib/Dialect/QUIR/Transforms/RemoveUnusedCircuits.cpp
- releasenotes/notes/add-merge-circuit-measures-e2b80378bf659793.yaml
- test/Dialect/QUIR/Transforms/merge-circuit-measures.mlir
- test/Dialect/QUIR/Transforms/merge-circuits.mlir
- test/Dialect/QUIR/Transforms/remove-unused-circuits.mlir
Adds a `MergeCircuitMeasuresPass` to merge `quir.measure`s inside circuits. Based on `MergeMeasuresTopologicalPass`.
Adds pass and test. 
Updates `MergeCircuitsPass` so that a `ParallelControlFlowOp` will block a merge.
The PR restores performance of merging measurements when circuits are enabled.
> Add MergeCircuitMeasuresPass

- test/Dialect/QUIR/Transforms/merge-circuit-measures.mlir
- test/Dialect/QUIR/Transforms/remove-unused-circuits.mlir
Removes unnecessary  `--dump-input always` from FileChecks left over from debugging.
> remove unnecessary  --dump-input

- lib/Dialect/QUIR/Transforms/MergeCircuitMeasures.cpp
Fixes a formatting issue with MergeCircuitMeasures causing check-format to fail.
> Fix formatting issue with MergeCircuitMeasures

- conan/clang-tools-extra/conanfile.py
- conan/llvm/conanfile.py
This PR disables LLVM_ENABLE_WARNINGS to reflect our internal environment. Some of the checks enabled by this flag will be added back in a separate PR.
> Disable LLVM_ENABLE_WARNINGS 

- conan/llvm/conanfile.py
This PR enables the python bindings for the LLVM that is cached in our Github actions conan cache. It is my hope that merging this PR and forcing a rebuild and save of the cached conan llvm package with this setting enabled will allow my PR #264 to pass CI.
> Enable python bindings for internal CI

- conan/llvm/conanfile.py
This PR is another attempt to update the conan cache so that the LLVM package builds with the python bindings enabled.
> Enable python bindings for internal CI attempt 2

- CMakeLists.txt
- cmake/AddWarnings.cmake
- conanfile.py
- releasenotes/notes/add-compile-warnings-9e80ff424ff16342.yaml
This PR adds LLVM style compiler warnings with the option to disable the warnings. 
The warnings are taken from llvm's [HandleLLVMOptions.cmake](https://github.com/llvm/llvm-project/blob/release/17.x/llvm/cmake/modules/HandleLLVMOptions.cmake) with a few exceptions:
1. MSVC / Clang-CL related tests are removed
2. covered-switch-default has been disabled
The usage of the warnings may be disabled by setting an option with:
`conan install .. -o enable_warnings=False` 
prior to running:
`conan build ..`
> Add LLVM style compile warnings 

- cmake/AddWarnings.cmake
Fixes cmake warning:
```
CMake Warning (dev) in qss-compiler/cmake/AddWarnings.cmake:
A logical block opening on the line
qss-compiler/cmake/AddWarnings.cmake:26 (if)
closes on the line
qss-compiler/cmake/AddWarnings.cmake:149 (endif)
with mis-matching arguments.
Call Stack (most recent call first):
qss-compiler/CMakeLists.txt:96 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.
```
> Fix cmake warning

- lib/Dialect/QUIR/Transforms/MergeCircuits.cpp
- test/Dialect/QUIR/Transforms/merge-circuit-issue-1833.mlir
Fixes bug in MergeCircuitsPass for handling operand / argument combining when the operands to a circuit is are not unique (that is an operand is repeated in the operand list).
> Fix for non-unique arguments to circuits

- include/API/errors.h
- lib/Frontend/OpenQASM3/OpenQASM3Frontend.cpp
- python_lib/qss_compiler/compile.py
- python_lib/qss_compiler/exceptions.py
- releasenotes/notes/soo-ER-raise-OpenQASM3ParseFailure-7db973ddd38ece7e.yaml
- test/python_lib/test_compile.py
`QSSCompilationFailure` error category is a generic error category and one of the test case which raises Error diagnostic in the parser will now raise `OpenQASM3ParseFailure`
> Replace few `QSSCompilationFailure` to `OpenQASM3ParseFailure`

- lib/Frontend/OpenQASM3/OpenQASM3Frontend.cpp
- python_lib/qss_compiler/compile.py
- python_lib/qss_compiler/exceptions.py
- releasenotes/notes/soo-ER-raise-OpenQASM3ParseFailure-7db973ddd38ece7e.yaml
- test/python_lib/test_compile.py
Backport changes made in https://github.com/openqasm/qe-compiler/pull/277
waiting on other back ports to merge.
> [Backport v3.8] Replace few `QSSCompilationFailure` to `OpenQASM3ParseFailure`

- include/API/errors.h
- include/HAL/TargetSystem.h
- lib/API/errors.cpp
- python_lib/qss_compiler/compile.py
- python_lib/qss_compiler/exceptions.py
- python_lib/qss_compiler/lib_enums.cpp
- releasenotes/notes/control-system-resources-exceeded-error-d2a2c15c52fa02dd.yaml
Backport of https://github.com/openqasm/qe-compiler/pull/256
> [Backport 3.8] Control systems resources exceeded

- lib/Dialect/QUIR/Transforms/MergeCircuitMeasures.cpp
Fixes `incorrect # of replacement values assert` when testing a debug build by correcting the number of values used when replacing an operation.
> [Backport 3.8] Fix incorrect # of replacement values assert for debug builds (#283)

- lib/HAL/TargetSystem.cpp
This allows modules that do not have a `quir.nodeType` attribute to exist and not cause compilation failures.
> Add toleration for modules that do not have a quir.nodeType attribute.

- include/Dialect/QUIR/Transforms/ExtractCircuits.h
- include/Dialect/QUIR/Utils/Utils.h
- lib/Dialect/QUIR/Transforms/ExtractCircuits.cpp
- lib/Dialect/QUIR/Utils/Utils.cpp
This PR improves the performance of the ExtractCircuitsPass by replacing `insertArguments` with `getBody().addArugment`.
Also fixes a bug by inserting call_circuit after location of last operation in circuit rather than the first.
---------
> [Backport 3.8] Extract Circuits Performance Improvement (#291)

- include/API/errors.h
- lib/API/errors.cpp
- python_lib/qss_compiler/compile.py
- python_lib/qss_compiler/exceptions.py
- python_lib/qss_compiler/lib_enums.cpp
- releasenotes/notes/control-system-resources-exceeded-error-d2a2c15c52fa02dd.yaml
This reverts commit e99ff5c863a310262adc4c6ddff18e43172e7682.
This reverts the addition of the `QSSControlSystemResourcesExceeded` error class as the code to actually emit that type of error has not been back ported to release_v3.8.
After discussions with the author @mbhealy it is our recommendation to not back port the code to emit the error as it was developed after the LLVM 17 update and associated refactors making the back port difficult.
> Revert "[Backport 3.8] Control systems resources exceeded (#281)"

- lib/Frontend/OpenQASM3/OpenQASM3Frontend.cpp
- test/python_lib/conftest.py
- test/python_lib/test_compile.py
Without the change made in this PR, a list of diagnostics with all kinds of `diagLevel`s are added to category `OpenQASM3ParseFailure`. This PR changes this behavior to just having `Error` and `Fatal` severity `diagLevel` in the  `OpenQASM3ParseFailure` category.
> Fix for when to add `OpenQASM3ParseFailure` to diagnostic

- lib/Dialect/QUIR/IR/QUIRInterfaces.cpp
- lib/Dialect/QUIR/Transforms/AngleConversion.cpp
- releasenotes/notes/optimize-greedy-rewrites-b042d4e824642f9a.yaml
Optimize a number of greedy rewrite passes. 
- QUIRAngleConversionPass: Goes from about ~7.5s for 100x100 to 0.9s on my machine
> Optimize greedy rewrite passes

- lib/Dialect/QUIR/IR/QUIRInterfaces.cpp
- lib/Dialect/QUIR/Transforms/AngleConversion.cpp
- releasenotes/notes/optimize-greedy-rewrites-b042d4e824642f9a.yaml
Optimize a number of greedy rewrite passes.
- QUIRAngleConversionPass: Goes from about ~7.5s for 100x100 to 0.9s on my machine
> [Backport] Optimize greedy rewrite passes (#298)

- include/Dialect/Pulse/Utils/Utils.h
- lib/Dialect/Pulse/Utils/Utils.cpp
This PR changes the return value of the Pulse utility method `getPhaseValue()` to return an `mlir::Value` instead of a `double`. 
This is necessary when using parameters, as the phase offset can be specified as a parameter value in addition to a compile time constant. By returning the `mlir::Value`, the caller of `phaseOffset` has the ability to differentiate between the two scenarios and act accordingly.
> Update getPhaseValue to return an mlir::Value.

- conan/qasm/conandata.yml
- conan/qasm/conanfile.py
- conandata.yml
- lib/Frontend/OpenQASM3/QUIRGenQASM3Visitor.cpp
- releasenotes/notes/add-bitnot-support-7ad288e5a87b7302.yaml
- test/Frontend/OpenQASM3/bitops.qasm
Hi Team,
I've added rules to parse "~" symbol in qe-qasm: https://github.com/openqasm/qe-qasm/pull/29, at the side of qe-compiler, we need to generate a MLIR op for `ASTOpTypeBitNot` in `lib/Frontend/OpenQASM3/QUIRGenQASM3Visitor.cpp`.
After searching, I find that MLIR does not have arith operations directly related to "BitNot". In the context of OQ3, I believe "~cbit" and "!cbit" are equivalent in a "if" condition? So I just simply reused the processing logic of `ASTOpTypeLogicalNot`, which checks whether the target is a `I1Type` and also works for `ASTOpTypeBitNot` operation. It will also create an `CmpIPredicate::ne` operation.
Willing to update my pr if you have better solutions
Thanks,
Yilun
1. Update the commit id of qe-qasm project
2. Reuse the processing logic of …
> fix: support ~ operation, close #278

- conan/qasm/conandata.yml
- conan/qasm/conanfile.py
- conandata.yml
- test/python_lib/conftest.py
- test/python_lib/test_compile.py
This PR adds tests for the updates made in https://github.com/openqasm/qe-qasm/pull/34. This update is made so that the compiler doesn't fail assertion, but instead raises appropriate errors
> Raise `OpenQASM3ParseFailure` instead of `QSSCompilerEOFFailure`

- lib/Dialect/QUIR/Transforms/ExtractCircuits.cpp
- test/Dialect/QUIR/Transforms/extract-circuits.mlir
Fixes bug where ExtractCircuits did not properly terminate a circuit on a `qcs.synchronize`
> Terminate circuit on qcs.synchronize

- lib/Dialect/QUIR/Transforms/ExtractCircuits.cpp
- test/Dialect/QUIR/Transforms/extract-circuits.mlir
Fixes bug where ExtractCircuits did not properly terminate a circuit on a `qcs.synchronize`
> [Backport 3.8] Terminate circuit on qcs.synchronize (#307)

- .clang-tidy
- lib/Dialect/QUIR/Transforms/ExtractCircuits.cpp
- tools/qss-opt/qss-opt.cpp
Removes clang tidy's preference for anonymous namespaces in favor of LLVM coding guidelines.
> Remove clang tidy check for misc-use-anonymous-namespace

- include/API/errors.h
- include/Frontend/OpenQASM3/OpenQASM3Frontend.h
- include/Frontend/OpenQASM3/QUIRGenQASM3Visitor.h
- lib/API/api.cpp
- lib/API/errors.cpp
- lib/Frontend/OpenQASM3/OpenQASM3Frontend.cpp
- lib/Frontend/OpenQASM3/QUIRGenQASM3Visitor.cpp
- python_lib/qss_compiler/compile.py
- python_lib/qss_compiler/examples/parse.py
- python_lib/qss_compiler/examples/pulse.py
- python_lib/qss_compiler/exceptions.py
- python_lib/qss_compiler/lib.cpp
- python_lib/qss_compiler/lib_enums.cpp
- python_lib/qss_compiler/link.py
- releasenotes/notes/add-qssc-error-reporting-mechanisms-82fa32e30d30ccce.yaml
- releasenotes/notes/add-unsupported-openqasm3-input-a584bb990cd9c9ff.yaml
- targets/systems/mock/Conversion/QUIRToStandard/QUIRToStandard.cpp
- targets/systems/mock/Transforms/QubitLocalization.cpp
- targets/systems/mock/Transforms/QubitLocalization.h
- targets/systems/mock/test/python_lib/test_compile_mock.py
- test/Frontend/OpenQASM3/diagnostics-parse-error.qasm
- test/Frontend/OpenQASM3/diagnostics-unsupported-error.qasm
- test/python_lib/conftest.py
- test/python_lib/test_compile.py
Closes #236. This PR adds support for returning diagnostics for OpenQASM3 generation errors. It also adds an extension to the MLIR diagnostics engine for returning qss-compiler diagnostics within any pass or context with better diagnostic handling through MLIR's builtin diagnostic handlers.
Returning a QSSC diagnostic from a pass should be as simple as
```
qssc::emitError(op, cat) << "Message";
```
> Add qasm3 generation error handling

- include/API/errors.h
- include/Frontend/OpenQASM3/OpenQASM3Frontend.h
- include/Frontend/OpenQASM3/QUIRGenQASM3Visitor.h
- lib/API/api.cpp
- lib/API/errors.cpp
- lib/Frontend/OpenQASM3/OpenQASM3Frontend.cpp
- lib/Frontend/OpenQASM3/QUIRGenQASM3Visitor.cpp
- python_lib/qss_compiler/compile.py
- python_lib/qss_compiler/examples/parse.py
- python_lib/qss_compiler/examples/pulse.py
- python_lib/qss_compiler/exceptions.py
- python_lib/qss_compiler/lib.cpp
- python_lib/qss_compiler/lib_enums.cpp
- python_lib/qss_compiler/link.py
- releasenotes/notes/add-qssc-error-reporting-mechanisms-82fa32e30d30ccce.yaml
- releasenotes/notes/add-unsupported-openqasm3-input-a584bb990cd9c9ff.yaml
- targets/systems/mock/Conversion/QUIRToStandard/QUIRToStandard.cpp
- targets/systems/mock/Transforms/QubitLocalization.cpp
- targets/systems/mock/Transforms/QubitLocalization.h
- targets/systems/mock/test/python_lib/test_compile_mock.py
- test/Frontend/OpenQASM3/diagnostics-parse-error.qasm
- test/Frontend/OpenQASM3/diagnostics-unsupported-error.qasm
- test/python_lib/conftest.py
- test/python_lib/test_compile.py
Backports support for returning diagnostics for OpenQASM3 generation errors. It also adds an extension to the MLIR diagnostics engine for returning qss-compiler diagnostics within any pass or context with better diagnostic handling through MLIR's builtin diagnostic handlers.
Returning a QSSC diagnostic from a pass should be as simple as
```
qssc::emitError(op, cat) << "Message";
```
> [Backport 3.9] Add qasm3 generation error handling (#306)

- include/Conversion/QUIRToPulse/QUIRToPulse.h
- include/Dialect/Pulse/Transforms/SchedulePort.h
- include/Dialect/Pulse/Transforms/Scheduling.h
- include/Dialect/QUIR/Transforms/BreakReset.h
- include/Dialect/QUIR/Transforms/ExtractCircuits.h
- include/Dialect/QUIR/Transforms/MergeCircuits.h
- include/Dialect/QUIR/Transforms/SubroutineCloning.h
- include/Utils/SymbolCacheAnalysis.h
- lib/Conversion/QUIRToPulse/QUIRToPulse.cpp
- lib/Dialect/Pulse/Transforms/SchedulePort.cpp
- lib/Dialect/Pulse/Transforms/Scheduling.cpp
- lib/Dialect/QUIR/Transforms/BreakReset.cpp
- lib/Dialect/QUIR/Transforms/ExtractCircuits.cpp
- lib/Dialect/QUIR/Transforms/MergeCircuitMeasures.cpp
- lib/Dialect/QUIR/Transforms/MergeCircuits.cpp
- lib/Dialect/QUIR/Transforms/SubroutineCloning.cpp
- releasenotes/notes/symbol-cache-analysis-e135ccc3fe625e2e.yaml
Adds a SymbolCacheAnalysis to standardizing the caching of symbols for Circuits, Sequences and other function like operations which follow a call_<name> by callee, <name> @callee pattern.
> [Backport] Add Symbol Cache Analysis (#301)

- lib/Dialect/QCS/Utils/ParameterInitialValueAnalysis.cpp
- test/Dialect/QCS/Utils/parameter-initial-value-analysis.mlir
This PR adjusts the ParameterInitialValueAnalysis so that it will search the current module for parameter definitions and then search parent modules if parameters are not found.
> search upward for parameters

- lib/Dialect/QCS/Utils/ParameterInitialValueAnalysis.cpp
- test/Dialect/QCS/Utils/parameter-initial-value-analysis.mlir
Adjust the ParameterInitialValueAnalysis so that it will search the current module for parameter definitions and then search parent modules if parameters are not found.
Cherry-pick to test_1 branch
> [Backport] search upward for parameters (#320)

- include/Dialect/Pulse/Utils/Utils.h
- lib/Conversion/QUIRToPulse/LoadPulseCals.cpp
- lib/Conversion/QUIRToPulse/QUIRToPulse.cpp
Remove qubit arguments from qcs.syncronize when converting to pulse.
> remove qubits from SynchronizeOp

- lib/Frontend/OpenQASM3/QUIRGenQASM3Visitor.cpp
- releasenotes/notes/default-only-switch-64bb951256d7d2b5.yaml
- test/Frontend/OpenQASM3/switch-default-only.qasm3
This PR fixes a problem in QUIRGenQasm3Visitor that was causing segmentation faults when verifying switch statements that contain only a default region.
> Fix default-only switch statements

- lib/Frontend/OpenQASM3/QUIRGenQASM3Visitor.cpp
- releasenotes/notes/default-only-switch-64bb951256d7d2b5.yaml
- test/Frontend/OpenQASM3/switch-default-only.qasm3
Backport of https://github.com/openqasm/qe-compiler/pull/324
> [Backport 3.9] Fix default only switch

- include/Dialect/QCS/IR/QCSOps.td
- include/Dialect/QCS/Utils/ParameterInitialValueAnalysis.h
- include/Dialect/QUIR/Transforms/QUIRCircuitAnalysis.h
- include/Frontend/OpenQASM3/QUIRGenQASM3Visitor.h
- lib/Dialect/QCS/IR/QCSOps.cpp
- lib/Dialect/QCS/Utils/ParameterInitialValueAnalysis.cpp
- lib/Dialect/QUIR/Transforms/LoadElimination.cpp
- lib/Dialect/QUIR/Transforms/QUIRCircuitAnalysis.cpp
- lib/Frontend/OpenQASM3/QUIRGenQASM3Visitor.cpp
- lib/Frontend/OpenQASM3/QUIRVariableBuilder.cpp
- test/Dialect/QCS/Utils/parameter-initial-value-analysis.mlir
- test/Dialect/QUIR/Transforms/load-elimination2.mlir
- test/Frontend/OpenQASM3/input-parameters-if.qasm
- test/Frontend/OpenQASM3/input-parameters-while.qasm
- test/Frontend/OpenQASM3/input-parameters.qasm
Improves performance of compilation when using parameters by dropping the use of the DeclareParameterOp and resulting symbol lookup. The initial value has been moved to an attribute of the ParameterLoadOp. Removes the use of ParameterInitialValueAnalysis.
> Parameters Compiling Performance Improvements 

- include/Dialect/QCS/IR/QCSOps.td
- include/Dialect/QCS/Utils/ParameterInitialValueAnalysis.h
- include/Dialect/QUIR/Transforms/QUIRCircuitAnalysis.h
- include/Frontend/OpenQASM3/QUIRGenQASM3Visitor.h
- lib/Dialect/QCS/IR/QCSOps.cpp
- lib/Dialect/QCS/Utils/ParameterInitialValueAnalysis.cpp
- lib/Dialect/QUIR/Transforms/LoadElimination.cpp
- lib/Dialect/QUIR/Transforms/QUIRCircuitAnalysis.cpp
- lib/Frontend/OpenQASM3/QUIRGenQASM3Visitor.cpp
- lib/Frontend/OpenQASM3/QUIRVariableBuilder.cpp
- test/Dialect/QCS/Utils/parameter-initial-value-analysis.mlir
- test/Dialect/QUIR/Transforms/load-elimination2.mlir
- test/Frontend/OpenQASM3/input-parameters-if.qasm
- test/Frontend/OpenQASM3/input-parameters-while.qasm
- test/Frontend/OpenQASM3/input-parameters.qasm
Improves performance of compilation when using parameters by dropping the use of the DeclareParameterOp and resulting symbol lookup. The initial value has been moved to an attribute of the ParameterLoadOp. Removes the use of ParameterInitialValueAnalysis.
> [Backport] Parameters Compiling Performance Improvements  (#330)

- include/API/api.h
- include/Arguments/Arguments.h
- lib/API/api.cpp
- lib/Arguments/Arguments.cpp
- python_lib/qss_compiler/lib.cpp
- python_lib/qss_compiler/link.py
- releasenotes/notes/link-threading-d295374d01595205.yaml
Adds threading support to the updateParameters method used in bindArguments. This will create threads for the patch point expression conversion from string to a calculated value. 
The number of threads is controlled by the python interfaces `number_of_threads` option:
* `-1`: set to number of CPUs reported
* `0`: diable
* `> 1`: limit
defaults to -1
Testing indicates that the majority of time in spent in the [zip_close](https://github.com/openqasm/qe-compiler/blob/1f506a70e51a042c9e21767faa1aa24720c016c5/lib/Payload/ZipPayload/PatchableZipPayload.cpp#L183)  line limiting opportunities for applying additional parallelism.
> add threading to updateParameters

- include/API/api.h
- include/Arguments/Arguments.h
- lib/API/api.cpp
- lib/Arguments/Arguments.cpp
- python_lib/qss_compiler/lib.cpp
- python_lib/qss_compiler/link.py
- releasenotes/notes/link-threading-d295374d01595205.yaml
Adds threading support to the updateParameters method used in bindArguments. This will create threads for the patch point expression conversion from string to a calculated value.
> [Backport] add threading to updateParameters (#332)

- conan/qasm/conandata.yml
- conan/qasm/conanfile.py
- conandata.yml
- include/Conversion/QUIRToPulse/QUIRToPulse.h
- include/Dialect/QUIR/Transforms/ExtractCircuits.h
- include/Frontend/OpenQASM3/QUIRGenQASM3Visitor.h
- include/Frontend/OpenQASM3/QUIRVariableBuilder.h
- lib/Conversion/QUIRToPulse/LoadPulseCals.cpp
- lib/Conversion/QUIRToPulse/QUIRToPulse.cpp
- lib/Dialect/Pulse/IR/PulseOps.cpp
- lib/Dialect/Pulse/Transforms/Scheduling.cpp
- lib/Dialect/QUIR/IR/QUIROps.cpp
- lib/Dialect/QUIR/Transforms/ExtractCircuits.cpp
- lib/Dialect/QUIR/Transforms/ReorderMeasurements.cpp
- lib/Dialect/QUIR/Transforms/UnusedVariable.cpp
- lib/Frontend/OpenQASM3/QUIRGenQASM3Visitor.cpp
- lib/Frontend/OpenQASM3/QUIRVariableBuilder.cpp
- releasenotes/notes/update-parameter-handling-cfa04a0bd7250401.yaml
- test/Dialect/QUIR/Transforms/extract-circuits.mlir
- test/Dialect/QUIR/Transforms/reorder-measurements.mlir
- test/Frontend/OpenQASM3/input-output-variables.qasm
- test/Frontend/OpenQASM3/input-parameters-if.qasm
- test/Frontend/OpenQASM3/input-parameters-while.qasm
- test/Frontend/OpenQASM3/input-parameters.qasm
- test/unittest/quir-dialect.cpp
This PR updates how parameters are handled. They are now directly read from "parameter_load" ops which removes the need for QUIR variable analysis and casting which significantly improves performance of large parameter programs by reducing the total number of operations in the program. This also cuts down on the total number of arguments to each circuit/sequence by storing the parameter loads/constants directly in the sequence itself
For example before for the program below
```qasm
OPENQASM 3;
qubit $0;
qubit $1;
qubit $2;
gate sx q { }
gate rz(phi) q { }
input float[64] theta = 3.14159265358979;
input angle phi;
sx $0;
rz(theta) $0;
sx $0;
rz(phi) $1;
rz(3.141592) $1;
rz(theta) $2;
rz(phi) $2;
bit b;
b = measure $0;
```
The MLIR generated is now:
```mlir
module {
func.func @sx(%arg0: …
```
> [Backport 3.10]Update parameter/constant op handling for performance (#335)

- include/Utils/SymbolCacheAnalysis.h
- lib/Dialect/QUIR/Utils/Utils.cpp
- releasenotes/notes/symbol-cache-use-densemap-c178e05e59c41bbe.yaml
> [Backport 3.10] Reduce memory usage in pulse sequencing  (#336)
